default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: P@ssworld

development:
  <<: *default
  database: rails-on-docker-demo_development

test:
  <<: *default
  database: rails-on-docker-demo_test

production:
  <<: *default
  database: rails-on-docker-demo_production
  username: rails-on-docker-demo
  password: <%= ENV['RAILS-ON-DOCKER-DEMO_DATABASE_PASSWORD'] %>
